// Computes the vendored (generated) shared files every skill should contain.
// Used by sync-shared.mjs (writes) and check-shared.mjs (verifies).

import { readFileSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';
import {
  ROOT, SKILLS_DIR, modulesFor, vendoredPath, generatedHeader, firstHeading, markdownLinks, isExternal,
} from './repo.mjs';

/**
 * Returns { files: Map<absPath, content>, problems: string[] }.
 * `problems` lists source-level issues (missing modules, basename collisions, relative links in
 * shared markdown) that make vendoring unsafe.
 */
export function computeVendored(catalog) {
  const files = new Map();
  const problems = [];
  const basenames = new Map();
  const brief = catalog.coreBrief && existsSync(join(ROOT, catalog.coreBrief))
    ? readFileSync(join(ROOT, catalog.coreBrief), 'utf8').trim()
    : null;
  if (catalog.coreBrief && !brief) problems.push(`coreBrief "${catalog.coreBrief}" does not exist`);

  for (const skill of catalog.skills) {
    // The core brief is inlined into SKILL.md itself: the body is the only part of a skill an agent
    // reliably reads (evals showed "read experience-core.md first" was usually skipped).
    if (brief) {
      const skillPath = join(SKILLS_DIR, skill.name, 'SKILL.md');
      const text = existsSync(skillPath) ? readFileSync(skillPath, 'utf8') : '';
      const block = /<!-- core-brief:start[^>]*-->[\s\S]*?<!-- core-brief:end -->/;
      if (!block.test(text)) problems.push(`${skill.name}: SKILL.md has no <!-- core-brief:start --> … <!-- core-brief:end --> markers`);
      else files.set(skillPath, text.replace(block, () => `${CORE_BRIEF_START}\n${brief}\n<!-- core-brief:end -->`));
    }
    const modules = modulesFor(catalog, skill);
    const indexRows = [];
    for (const source of modules) {
      const abs = join(ROOT, source);
      if (!/^(shared|examples)\//.test(source)) {
        problems.push(`${skill.name}: shared module "${source}" must live under shared/ or examples/`);
        continue;
      }
      if (!existsSync(abs)) {
        problems.push(`${skill.name}: shared module "${source}" does not exist`);
        continue;
      }
      const name = basename(source);
      const seen = basenames.get(name);
      if (seen && seen !== source) problems.push(`Basename collision: "${source}" and "${seen}" both vendor as ${name}`);
      basenames.set(name, source);

      const text = readFileSync(abs, 'utf8');
      if (source.endsWith('.md')) {
        for (const link of markdownLinks(text)) {
          if (!isExternal(link.target)) {
            problems.push(`${source}:${link.line}: relative link "${link.target}" would break when vendored; refer to other modules by name`);
          }
        }
        indexRows.push(`| \`${name}\` | ${firstHeading(text).replace(/\|/g, '\\|')} | \`${source}\` |`);
      }
      files.set(vendoredPath(skill.name, source), generatedHeader(source) + text);
    }
    if (indexRows.length) {
      const index = [
        '<!-- GENERATED BY scripts/sync-shared.mjs. DO NOT EDIT DIRECTLY. -->',
        '',
        '# Shared references',
        '',
        `Shared philosophy, taxonomies, patterns, and worked examples vendored into **${skill.name}**`,
        'so the skill works when installed on its own. Load a file only when the skill\'s workflow',
        'points to it.',
        '',
        '| File | Topic | Source in the collection |',
        '|---|---|---|',
        ...indexRows,
        '',
      ].join('\n');
      files.set(join(SKILLS_DIR, skill.name, 'references', '_shared', 'README.md'), index);
    }
  }
  return { files, problems };
}

export const CORE_BRIEF_START = '<!-- core-brief:start · GENERATED FROM shared/philosophy/core-brief.md by npm run sync. Do not edit here. -->';

export const VENDORED_DIRS = ['references/_shared', 'scripts/_shared'];
